//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class InstitucionEntities3 : DbContext
{
    public InstitucionEntities3()
        : base("name=InstitucionEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
    public DbSet<ALUMNO> ALUMNO { get; set; }
    public DbSet<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public DbSet<ARCHIVO> ARCHIVO { get; set; }
    public DbSet<CALIFICACION> CALIFICACION { get; set; }
    public DbSet<CATALOGO> CATALOGO { get; set; }
    public DbSet<CURSO> CURSO { get; set; }
    public DbSet<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public DbSet<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public DbSet<INSTITUCION> INSTITUCION { get; set; }
    public DbSet<LIBRO> LIBRO { get; set; }
    public DbSet<MATERIA> MATERIA { get; set; }
    public DbSet<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
    public DbSet<NOTICIA> NOTICIA { get; set; }
    public DbSet<NOTIFICACION> NOTIFICACION { get; set; }
    public DbSet<PARALELO> PARALELO { get; set; }
    public DbSet<PARCIAL> PARCIAL { get; set; }
    public DbSet<PERIODO> PERIODO { get; set; }
    public DbSet<PROFESOR> PROFESOR { get; set; }
    public DbSet<TUTOR> TUTOR { get; set; }
    public DbSet<USUARIO> USUARIO { get; set; }
}
