//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class InstitucionEntities : DbContext
{
    public InstitucionEntities()
        : base("name=InstitucionEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<ACTIVIDAD> ACTIVIDADs { get; set; }
    public DbSet<ALUMNO> ALUMNOes { get; set; }
    public DbSet<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public DbSet<ARCHIVO> ARCHIVOes { get; set; }
    public DbSet<CALIFICACION> CALIFICACIONs { get; set; }
    public DbSet<CURSO> CURSOes { get; set; }
    public DbSet<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public DbSet<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public DbSet<INSTITUCION> INSTITUCIONs { get; set; }
    public DbSet<LIBRO> LIBROes { get; set; }
    public DbSet<MATERIA> MATERIAs { get; set; }
    public DbSet<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
    public DbSet<NOTICIA> NOTICIAs { get; set; }
    public DbSet<NOTIFICACION> NOTIFICACIONs { get; set; }
    public DbSet<PARALELO> PARALELOes { get; set; }
    public DbSet<PARCIAL> PARCIALs { get; set; }
    public DbSet<PERIODO> PERIODOes { get; set; }
    public DbSet<PROFESOR> PROFESORs { get; set; }
    public DbSet<TUTOR> TUTORs { get; set; }
    public DbSet<USUARIO> USUARIOs { get; set; }
    public DbSet<CATALOGO> CATALOGOes { get; set; }
}
