//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVIDAD
{
    public int ACTIVIDADID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class ALUMNO
{
    public ALUMNO()
    {
        this.ALUMNO_NOTIFICACION = new HashSet<ALUMNO_NOTIFICACION>();
        this.MATERIA_ALUMNO = new HashSet<MATERIA_ALUMNO>();
    }

    public int ALUMNOID { get; set; }
    public Nullable<int> TUTORID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
    public string GENERO { get; set; }
    public string CEDULA { get; set; }

    public virtual ICollection<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public virtual TUTOR TUTOR { get; set; }
    public virtual ICollection<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
}

public partial class ALUMNO_NOTIFICACION
{
    public int ALUMNONOTIFICACIONID { get; set; }
    public Nullable<int> NOTIFICACIONID { get; set; }
    public Nullable<int> ALUMNOID { get; set; }

    public virtual ALUMNO ALUMNO { get; set; }
    public virtual NOTIFICACION NOTIFICACION { get; set; }
}

public partial class ARCHIVO
{
    public ARCHIVO()
    {
        this.LIBRO = new HashSet<LIBRO>();
        this.NOTIFICACION = new HashSet<NOTIFICACION>();
    }

    public int ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRPCION { get; set; }
    public byte[] DATA { get; set; }

    public virtual ICollection<LIBRO> LIBRO { get; set; }
    public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; }
}

public partial class CALIFICACION
{
    public int CALIFICACIONID { get; set; }
    public Nullable<int> MATERIAALUMNOID { get; set; }
    public Nullable<int> VALOR { get; set; }
    public string OBSERVACION { get; set; }
    public Nullable<int> PARCIALID { get; set; }
    public Nullable<int> PARCIAL2 { get; set; }
    public Nullable<int> PARCIAL3 { get; set; }
    public Nullable<int> PARCIAL1 { get; set; }

    public virtual MATERIA_ALUMNO MATERIA_ALUMNO { get; set; }
}

public partial class CATALOGO
{
    public int CATALOGOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }
    public string TIPO { get; set; }
}

public partial class CURSO
{
    public CURSO()
    {
        this.CURSO_MATEIRA = new HashSet<CURSO_MATEIRA>();
        this.CURSO_PROFESOR = new HashSet<CURSO_PROFESOR>();
    }

    public int CURSOID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public Nullable<int> PARALELOID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public virtual ICollection<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public virtual INSTITUCION INSTITUCION { get; set; }
    public virtual PARALELO PARALELO { get; set; }
}

public partial class CURSO_MATEIRA
{
    public int CURSOMATERIAID { get; set; }
    public Nullable<int> CURSOID { get; set; }
    public Nullable<int> MATERIAID { get; set; }

    public virtual CURSO CURSO { get; set; }
    public virtual MATERIA MATERIA { get; set; }
}

public partial class CURSO_PROFESOR
{
    public int CURSOPROFESORID { get; set; }
    public Nullable<int> CURSOID { get; set; }
    public Nullable<int> PROFESORID { get; set; }

    public virtual CURSO CURSO { get; set; }
    public virtual PROFESOR PROFESOR { get; set; }
}

public partial class INSTITUCION
{
    public INSTITUCION()
    {
        this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
        this.CURSO = new HashSet<CURSO>();
        this.LIBRO = new HashSet<LIBRO>();
        this.NOTICIA = new HashSet<NOTICIA>();
    }

    public int INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
    public virtual ICollection<CURSO> CURSO { get; set; }
    public virtual ICollection<LIBRO> LIBRO { get; set; }
    public virtual ICollection<NOTICIA> NOTICIA { get; set; }
}

public partial class LIBRO
{
    public int LIBROID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public Nullable<int> ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual ARCHIVO ARCHIVO { get; set; }
    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class MATERIA
{
    public MATERIA()
    {
        this.CURSO_MATEIRA = new HashSet<CURSO_MATEIRA>();
        this.MATERIA_ALUMNO = new HashSet<MATERIA_ALUMNO>();
    }

    public int MATERIAID { get; set; }
    public Nullable<int> PERIDODOID { get; set; }
    public string NOMBRE { get; set; }
    public string PUNTOS { get; set; }

    public virtual ICollection<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public virtual ICollection<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
    public virtual PERIODO PERIODO { get; set; }
}

public partial class MATERIA_ALUMNO
{
    public MATERIA_ALUMNO()
    {
        this.CALIFICACION = new HashSet<CALIFICACION>();
    }

    public int MATERIAALUMNOID { get; set; }
    public Nullable<int> MATERIAID { get; set; }
    public Nullable<int> ALUMNOID { get; set; }

    public virtual ALUMNO ALUMNO { get; set; }
    public virtual ICollection<CALIFICACION> CALIFICACION { get; set; }
    public virtual MATERIA MATERIA { get; set; }
}

public partial class NOTICIA
{
    public int NOTICIAID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class NOTIFICACION
{
    public NOTIFICACION()
    {
        this.ALUMNO_NOTIFICACION = new HashSet<ALUMNO_NOTIFICACION>();
    }

    public int NOTIFICACIONID { get; set; }
    public Nullable<int> ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }

    public virtual ICollection<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public virtual ARCHIVO ARCHIVO { get; set; }
}

public partial class PARALELO
{
    public PARALELO()
    {
        this.CURSO = new HashSet<CURSO>();
    }

    public int PARALELOID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<CURSO> CURSO { get; set; }
}

public partial class PARCIAL
{
    public int PARCIALID { get; set; }
    public Nullable<int> PERIDODOID { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<int> NUMERO { get; set; }

    public virtual PERIODO PERIODO { get; set; }
}

public partial class PERIODO
{
    public PERIODO()
    {
        this.MATERIA = new HashSet<MATERIA>();
        this.PARCIAL = new HashSet<PARCIAL>();
    }

    public int PERIDODOID { get; set; }
    public string NOMBRE { get; set; }
    public Nullable<System.DateTime> FECHAINICIO { get; set; }
    public Nullable<System.DateTime> FECHAFIN { get; set; }

    public virtual ICollection<MATERIA> MATERIA { get; set; }
    public virtual ICollection<PARCIAL> PARCIAL { get; set; }
}

public partial class PROFESOR
{
    public PROFESOR()
    {
        this.CURSO_PROFESOR = new HashSet<CURSO_PROFESOR>();
    }

    public int PROFESORID { get; set; }
    public Nullable<int> USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIEMIENTO { get; set; }
    public string CEDULA { get; set; }
    public string GENERO { get; set; }

    public virtual ICollection<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class TUTOR
{
    public TUTOR()
    {
        this.ALUMNO = new HashSet<ALUMNO>();
    }

    public int TUTORID { get; set; }
    public Nullable<int> USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
    public string CEDULA { get; set; }
    public string GENERO { get; set; }

    public virtual ICollection<ALUMNO> ALUMNO { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class USUARIO
{
    public USUARIO()
    {
        this.PROFESOR = new HashSet<PROFESOR>();
        this.TUTOR = new HashSet<TUTOR>();
    }

    public int USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string CLAVE { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public Nullable<int> PERFIL { get; set; }

    public virtual ICollection<PROFESOR> PROFESOR { get; set; }
    public virtual ICollection<TUTOR> TUTOR { get; set; }
}
