//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

public partial class ACTIVIDAD
{
    public int ACTIVIDADID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class ALUMNO
{
    public ALUMNO()
    {
        this.ALUMNO_NOTIFICACION = new HashSet<ALUMNO_NOTIFICACION>();
        this.MATERIA_ALUMNO = new HashSet<MATERIA_ALUMNO>();
    }

    public int ALUMNOID { get; set; }
    public Nullable<int> TUTORID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
    public string GENERO { get; set; }
    public string CEDULA { get; set; }

    public virtual ICollection<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public virtual TUTOR TUTOR { get; set; }
    public virtual ICollection<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
}

public partial class ALUMNO_NOTIFICACION
{
    public int ALUMNONOTIFICACIONID { get; set; }
    public Nullable<int> NOTIFICACIONID { get; set; }
    public Nullable<int> ALUMNOID { get; set; }

    public virtual ALUMNO ALUMNO { get; set; }
    public virtual NOTIFICACION NOTIFICACION { get; set; }
}

public partial class ARCHIVO
{
    public ARCHIVO()
    {
        this.LIBROes = new HashSet<LIBRO>();
        this.NOTIFICACIONs = new HashSet<NOTIFICACION>();
    }

    public int ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRPCION { get; set; }

    public virtual ICollection<LIBRO> LIBROes { get; set; }
    public virtual ICollection<NOTIFICACION> NOTIFICACIONs { get; set; }
}

public partial class CALIFICACION
{
    public int CALIFICACIONID { get; set; }
    public Nullable<int> MATERIAALUMNOID { get; set; }
    public string VALOR { get; set; }
    public string OBSERVACION { get; set; }

    public virtual MATERIA_ALUMNO MATERIA_ALUMNO { get; set; }
}

public partial class CATALOGO
{

    private InstitucionEntities datos = null;

    public InstitucionEntities Datos
    {
        get
        {
            if (datos == null)
            {
                datos = new InstitucionEntities();
            }
            return datos;
        }
    }


    public CATALOGO addCatalogo(String nombre, String descripcion, String tipo)
    {
        CATALOGO catalog = new CATALOGO();
        catalog.CATALOGOID = 0;
        catalog.NOMBRE = nombre;
        catalog.DESCRIPCION = descripcion;
        catalog.TIPO = tipo;

        Datos.CATALOGOes.Add(catalog);
        Datos.SaveChanges();

        return catalog;
    }

    public int CATALOGOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }
    public string TIPO { get; set; }
}

public partial class CURSO
{
    public CURSO()
    {
        this.CURSO_MATEIRA = new HashSet<CURSO_MATEIRA>();
        this.CURSO_PROFESOR = new HashSet<CURSO_PROFESOR>();
    }

    public int CURSOID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public Nullable<int> PARALELOID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public virtual ICollection<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public virtual INSTITUCION INSTITUCION { get; set; }
    public virtual PARALELO PARALELO { get; set; }
}

public partial class CURSO_MATEIRA
{
    public int CURSOMATERIAID { get; set; }
    public Nullable<int> CURSOID { get; set; }
    public Nullable<int> MATERIAID { get; set; }

    public virtual CURSO CURSO { get; set; }
    public virtual MATERIA MATERIA { get; set; }
}

public partial class CURSO_PROFESOR
{
    public int CURSOPROFESORID { get; set; }
    public Nullable<int> CURSOID { get; set; }
    public Nullable<int> PROFESORID { get; set; }

    public virtual CURSO CURSO { get; set; }
    public virtual PROFESOR PROFESOR { get; set; }
}

public partial class INSTITUCION
{
    public INSTITUCION()
    {
        this.ACTIVIDADs = new HashSet<ACTIVIDAD>();
        this.CURSOes = new HashSet<CURSO>();
        this.LIBROes = new HashSet<LIBRO>();
        this.NOTICIAs = new HashSet<NOTICIA>();
        //this.USUARIOs = new HashSet<USUARIO>();
    }

    public int INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<ACTIVIDAD> ACTIVIDADs { get; set; }
    public virtual ICollection<CURSO> CURSOes { get; set; }
    public virtual ICollection<LIBRO> LIBROes { get; set; }
    public virtual ICollection<NOTICIA> NOTICIAs { get; set; }
    //public virtual ICollection<USUARIO> USUARIOs { get; set; }
}

public partial class LIBRO
{
    public int LIBROID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public Nullable<int> ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual ARCHIVO ARCHIVO { get; set; }
    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class MATERIA
{
    public MATERIA()
    {
        this.CURSO_MATEIRA = new HashSet<CURSO_MATEIRA>();
        this.MATERIA_ALUMNO = new HashSet<MATERIA_ALUMNO>();
    }

    public int MATERIAID { get; set; }
    public Nullable<int> PERIDODOID { get; set; }
    public string NOMBRE { get; set; }
    public string PUNTOS { get; set; }

    public virtual ICollection<CURSO_MATEIRA> CURSO_MATEIRA { get; set; }
    public virtual ICollection<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
    public virtual PERIODO PERIODO { get; set; }
}

public partial class MATERIA_ALUMNO
{
    public MATERIA_ALUMNO()
    {
        this.CALIFICACIONs = new HashSet<CALIFICACION>();
    }

    public int MATERIAALUMNOID { get; set; }
    public Nullable<int> MATERIAID { get; set; }
    public Nullable<int> ALUMNOID { get; set; }

    public virtual ALUMNO ALUMNO { get; set; }
    public virtual ICollection<CALIFICACION> CALIFICACIONs { get; set; }
    public virtual MATERIA MATERIA { get; set; }
}

public partial class NOTICIA
{
    public int NOTICIAID { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual INSTITUCION INSTITUCION { get; set; }
}

public partial class NOTIFICACION
{
    public NOTIFICACION()
    {
        this.ALUMNO_NOTIFICACION = new HashSet<ALUMNO_NOTIFICACION>();
    }

    public int NOTIFICACIONID { get; set; }
    public Nullable<int> ARCHIVOID { get; set; }
    public string NOMBRE { get; set; }
    public string DESCRIPCION { get; set; }

    public virtual ICollection<ALUMNO_NOTIFICACION> ALUMNO_NOTIFICACION { get; set; }
    public virtual ARCHIVO ARCHIVO { get; set; }
}

public partial class PARALELO
{
    public PARALELO()
    {
        this.CURSOes = new HashSet<CURSO>();
    }

    public int PARALELOID { get; set; }
    public string NOMBRE { get; set; }

    public virtual ICollection<CURSO> CURSOes { get; set; }
}

public partial class PARCIAL
{
    public int PARCIALID { get; set; }
    public Nullable<int> PERIDODOID { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<int> NUMERO { get; set; }

    public virtual PERIODO PERIODO { get; set; }
}

public partial class PERIODO
{
    public PERIODO()
    {
        this.MATERIAs = new HashSet<MATERIA>();
        this.PARCIALs = new HashSet<PARCIAL>();
    }

    public int PERIDODOID { get; set; }
    public string NOMBRE { get; set; }
    public Nullable<System.DateTime> FECHAINICIO { get; set; }
    public Nullable<System.DateTime> FECHAFIN { get; set; }

    public virtual ICollection<MATERIA> MATERIAs { get; set; }
    public virtual ICollection<PARCIAL> PARCIALs { get; set; }
}

public partial class PROFESOR
{
    public PROFESOR()
    {
        this.CURSO_PROFESOR = new HashSet<CURSO_PROFESOR>();
    }

    public int PROFESORID { get; set; }
    public Nullable<int> USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIEMIENTO { get; set; }
    public string CEDULA { get; set; }
    public string GENERO { get; set; }

    public virtual ICollection<CURSO_PROFESOR> CURSO_PROFESOR { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class TUTOR
{
    public TUTOR()
    {
        this.ALUMNOes = new HashSet<ALUMNO>();
    }

    public int TUTORID { get; set; }
    public Nullable<int> USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string NOMBRELARGO { get; set; }
    public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
    public string CEDULA { get; set; }
    public string GENERO { get; set; }

    public virtual ICollection<ALUMNO> ALUMNOes { get; set; }
    public virtual USUARIO USUARIO { get; set; }
}

public partial class USUARIO
{
    public USUARIO()
    {
        this.PROFESORs = new HashSet<PROFESOR>();
        this.TUTORs = new HashSet<TUTOR>();
    }  

    public int USUARIOID { get; set; }
    public string NOMBRE { get; set; }
    public string CLAVE { get; set; }
    public Nullable<int> INSTITUCIONID { get; set; }

    public virtual ICollection<PROFESOR> PROFESORs { get; set; }
    public virtual ICollection<TUTOR> TUTORs { get; set; }
}
